kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-quinoa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quinoa-app
  template:
    metadata:
      labels:
        app: java-quinoa-app
    spec:
      containers:
        - name: my-java-quinoa
          image: java-quinoa-image:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-java-quinoa-svc
spec:
ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
selector:
  app: java-quinoa-app